### ISSUE TITLE
update the bot to support latest dependencies 

### ISSUE THREAD

**Issue by Baggette** [jaketanda/Random-Image-Folder-to-Discord-Bot#3]
I know theres the new bot but I don't need all of those features all I need is a bot that posts pics from a folder. So if you could please update it to support latest dependencies.

**Comment by jaketanda** [comment]
Good point. It would be a bit of a pain to add all of those manually. I can try and think of a way to allow for both methods to exist (from a folder and using links), but otherwise, I'll just move forward with using the folder as it currently is.

**Comment by Daniel-MFG** [comment]
that would be really great if the new bot could support this...
And please also don't forget to add at least a ruff outline and explanation of what the new bot can do and how it works (as we don't know at all atm...)

**Comment by Daniel-MFG** [comment]
that would be awesome!
As a little idea for the send from folder feature: You could let the bot make a list of all files in the folder and use this as array... And then you use the index of the file in the array for the randomizer!
And to save resources when it runs you could only update this array when starting the bot...
(since only the bot admin can add files anyway)
This should make things easier for you ;P

**Comment by jaketanda** [comment]
Updated the bot to support the latest version of discord.js
